# Generated by Django 5.1.7 on 2025-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_task_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
