# Generated by Django 5.1.7 on 2025-04-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_due_date_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
