# Generated by Django 5.1.7 on 2025-03-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
